// Supabase-backed timetable service.
//   timetable_periods  — class period slot definitions (per school + year)
//   timetable_entries  — actual subject/teacher/room cell per (section, day, slot)
//
// Conflict detection runs in JS over the cache:
//   - same teacher booked in same day+slot
//   - inactive teacher
//   - timetable for closed academic year (write blocked)

import { supabase } from '@/lib/supabase';
import { apiTimetable } from '@/lib/apiClient';
import { useAuthStore } from '@/store/authStore';
import { useCorrectionStore } from '@/store/correctionStore';
import { useEditingYearStore } from '@/store/editingYearStore';
import { logAudit } from '@/lib/audit';
import { registerCacheResetter } from '@/lib/cacheBus';

export type TDay = 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday';
// Period type taxonomy. CLASS = teaching slot (needs a teacher).
// Everything else is non-teaching and skips the teacher picker in the
// edit modal. PRAYER / SHORT_BREAK / SPORTS_BREAK / NO_TEACHING /
// CUSTOM were added on top of the original 5 so principals can label
// the school day accurately. ASSEMBLY / BREAK / LUNCH / FREE stay for
// back-compat with rows generated by the older default slot set.
export type SlotType =
  | 'CLASS'
  | 'BREAK' | 'SHORT_BREAK' | 'SPORTS_BREAK'
  | 'LUNCH'
  | 'ASSEMBLY' | 'PRAYER'
  | 'NO_TEACHING'
  | 'CUSTOM'
  | 'FREE';

/** Slot types that do NOT require a teacher assignment. The slot-edit
 *  modal hides the teacher picker for these. */
export const NON_TEACHING_TYPES: SlotType[] = [
  'BREAK', 'SHORT_BREAK', 'SPORTS_BREAK', 'LUNCH',
  'ASSEMBLY', 'PRAYER', 'NO_TEACHING',
];

export interface PeriodSlot {
  slotId: string;
  label: string;
  startTime: string;
  endTime: string;
  type: SlotType;
  isFixed: boolean;
}

export interface TimetableEntry {
  id: string;
  classId: string;
  className: string;
  section: string;
  day: TDay;
  slotId: string;
  subject: string;
  teacherId: string;
  teacherName: string;
  room: string;
  academicYearId: string;
  /** 'TEACHING' (default) — regular subject + teacher.
   *  'ACTIVITY'           — per-day non-teaching designation (assembly /
   *                         lunch / prayer for this one day only).
   *                         Lets a single slot's behaviour vary by day
   *                         without mutating the school-wide slot.type
   *                         on timetable_periods. Migration 0131. */
  entryKind: 'TEACHING' | 'ACTIVITY';
}

export interface TimetableTeacher {
  id: string;
  name: string;
  subject: string;
}

export const DAYS: TDay[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

// Default slots — used until the school configures their own row in timetable_periods.
const DEFAULT_SLOTS: PeriodSlot[] = [
  { slotId: 'assembly', label: 'Assembly', startTime: '08:00', endTime: '08:20', type: 'ASSEMBLY', isFixed: true },
  { slotId: 'p1', label: 'Period 1', startTime: '08:20', endTime: '09:05', type: 'CLASS', isFixed: false },
  { slotId: 'p2', label: 'Period 2', startTime: '09:05', endTime: '09:50', type: 'CLASS', isFixed: false },
  { slotId: 'break', label: 'Short Break', startTime: '09:50', endTime: '10:05', type: 'BREAK', isFixed: true },
  { slotId: 'p3', label: 'Period 3', startTime: '10:05', endTime: '10:50', type: 'CLASS', isFixed: false },
  { slotId: 'p4', label: 'Period 4', startTime: '10:50', endTime: '11:35', type: 'CLASS', isFixed: false },
  { slotId: 'lunch', label: 'Lunch Break', startTime: '11:35', endTime: '12:15', type: 'LUNCH', isFixed: true },
  { slotId: 'p5', label: 'Period 5', startTime: '12:15', endTime: '13:00', type: 'CLASS', isFixed: false },
  { slotId: 'p6', label: 'Period 6', startTime: '13:00', endTime: '13:45', type: 'CLASS', isFixed: false },
];

export let PERIOD_SLOTS: PeriodSlot[] = [...DEFAULT_SLOTS];

/** "HH:MM" string compare-based overlap check. Two ranges [aS,aE) and [bS,bE)
 *  overlap iff aS < bE && bS < aE. Touching boundaries (aE === bS) do NOT
 *  conflict — back-to-back periods are allowed. */
function _timesOverlap(aStart: string, aEnd: string, bStart: string, bEnd: string): boolean {
  return aStart < bEnd && bStart < aEnd;
}

function getSchoolId(): string {
  const id = useAuthStore.getState().session?.schoolId;
  if (!id) throw new Error('No school in session');
  return id;
}

let _entriesCache: TimetableEntry[] = [];
let _teachersCache: TimetableTeacher[] = [];
let _activeYearId: string | null = null;
let _yearIsClosed = false;

// Wired to the cache bus so AcademicYearContext flushes us on year switch —
// the cached entries + resolved active year id belong to the previous year.
registerCacheResetter(() => {
  _entriesCache = [];
  _teachersCache = [];
  _activeYearId = null;
  _yearIsClosed = false;
});

interface EntryRow {
  id: string; section_id: string; class_id: string;
  day: string; slot_id: string;
  subject: string | null; teacher_id: string | null;
  teacher_name: string | null; room: string | null;
  academic_year_id: string;
  entry_kind: string | null;
  sections: { class_name: string; section: string } | null;
}

async function _loadActiveYear(schoolId: string): Promise<void> {
  // Honor Correction Mode override when set — load the closed year being
  // corrected instead of the school's currently-active year.
  const override = useEditingYearStore.getState().getEditingYearId();
  if (override) {
    const { data } = await supabase
      .from('academic_years').select('id, is_closed')
      .eq('school_id', schoolId).eq('id', override).maybeSingle();
    const ay = data as { id: string; is_closed: boolean } | null;
    _activeYearId = ay?.id ?? null;
    _yearIsClosed = !!ay?.is_closed;
    return;
  }
  const { data } = await supabase
    .from('academic_years').select('id, is_closed')
    .eq('school_id', schoolId).eq('is_active', true).maybeSingle();
  const ay = data as { id: string; is_closed: boolean } | null;
  _activeYearId = ay?.id ?? null;
  _yearIsClosed = !!ay?.is_closed;
}

// In-memory cache of ALL rows for the active (school, year). The
// service splits these into a per-class slot list on demand:
//   • class-specific rows (class_name = X) win for class X
//   • else rows with class_name = NULL act as the school default
//   • else hard-coded DEFAULT_SLOTS
// PERIOD_SLOTS itself stays as the *current* class's resolved set so
// existing consumers (refreshAll callers, getClassWeeklyMap, etc.)
// keep working without rewrites.
interface PeriodRow {
  id: string; name: string; start_time: string; end_time: string;
  period_type: string; sort_order: number; class_name: string | null;
}
let _periodRows: PeriodRow[] = [];

function _resolveSlotsForClass(className: string | null): PeriodSlot[] {
  const rowToSlot = (r: PeriodRow): PeriodSlot => ({
    slotId: r.id, label: r.name, startTime: r.start_time, endTime: r.end_time,
    type: (r.period_type as SlotType) ?? 'CLASS',
    isFixed: NON_TEACHING_TYPES.includes((r.period_type as SlotType) ?? 'CLASS'),
  });
  if (className) {
    const specific = _periodRows.filter(r => r.class_name === className).sort((a, b) => a.sort_order - b.sort_order);
    if (specific.length) return specific.map(rowToSlot);
  }
  const fallback = _periodRows.filter(r => !r.class_name).sort((a, b) => a.sort_order - b.sort_order);
  if (fallback.length) return fallback.map(rowToSlot);
  return [...DEFAULT_SLOTS];
}

async function _loadPeriods(schoolId: string): Promise<void> {
  if (!_activeYearId) return;
  const { data, error } = await supabase
    .from('timetable_periods')
    .select('id, name, start_time, end_time, period_type, sort_order, class_name')
    .eq('school_id', schoolId).eq('academic_year_id', _activeYearId)
    .order('sort_order');
  if (error) throw new Error(error.message);
  _periodRows = (data ?? []) as PeriodRow[];
  // Default PERIOD_SLOTS = school-default (class_name IS NULL) view.
  // Components that want a class-specific set call
  // timetableService.getSlotsForClass(className).
  PERIOD_SLOTS = _resolveSlotsForClass(null);
}

async function _loadEntries(schoolId: string): Promise<void> {
  if (!_activeYearId) { _entriesCache = []; return; }
  const { data, error } = await supabase
    .from('timetable_entries')
    .select('id, section_id, class_id, day, slot_id, subject, teacher_id, teacher_name, room, academic_year_id, entry_kind, sections(class_name, section)')
    .eq('school_id', schoolId).eq('academic_year_id', _activeYearId);
  if (error) throw new Error(error.message);
  _entriesCache = ((data ?? []) as unknown as EntryRow[]).map(r => ({
    id: r.id,
    classId: r.class_id,
    className: r.sections?.class_name ?? '',
    section: r.sections?.section ?? '',
    day: r.day as TDay,
    slotId: r.slot_id,
    subject: r.subject ?? '',
    teacherId: r.teacher_id ?? '',
    teacherName: r.teacher_name ?? '',
    room: r.room ?? '',
    academicYearId: r.academic_year_id,
    entryKind: r.entry_kind === 'ACTIVITY' ? 'ACTIVITY' : 'TEACHING',
  }));
}

async function _loadTeachers(schoolId: string): Promise<void> {
  const { data, error } = await supabase
    .from('staff').select('id, name, subject')
    .eq('school_id', schoolId).eq('is_active', true).eq('role', 'TEACHER')
    .order('name');
  if (error) throw new Error(error.message);
  _teachersCache = ((data ?? []) as { id: string; name: string; subject: string | null }[])
    .map(t => ({ id: t.id, name: t.name, subject: t.subject ?? '' }));
}


export const timetableService = {
  async refreshAll(): Promise<void> {
    const schoolId = getSchoolId();
    await _loadActiveYear(schoolId);
    await Promise.all([_loadPeriods(schoolId), _loadEntries(schoolId), _loadTeachers(schoolId)]);
  },

  getTeachers(): TimetableTeacher[] {
    return [..._teachersCache];
  },

  getClassTimetable(classId: string, _academicYearId?: string): TimetableEntry[] {
    return _entriesCache.filter(e => e.classId === classId);
  },

  getTeacherSchedule(teacherId: string, _academicYearId?: string): TimetableEntry[] {
    return _entriesCache.filter(e => e.teacherId === teacherId);
  },

  hasConflict(teacherId: string, day: TDay, slotId: string, excludeId?: string): TimetableEntry | null {
    // Catch BOTH same-slot collisions and time-range overlaps with other slots.
    // Two slots that share even a minute (e.g. Prayer 08:00-09:00 + Period-1
    // 08:30-09:30) must conflict for the same teacher on the same day.
    const target = PERIOD_SLOTS.find(s => s.slotId === slotId);
    if (!target) return null;
    return _entriesCache.find(e => {
      if (e.teacherId !== teacherId || e.day !== day || e.id === excludeId) return false;
      if (e.slotId === slotId) return true;
      const other = PERIOD_SLOTS.find(s => s.slotId === e.slotId);
      if (!other) return false;
      return _timesOverlap(target.startTime, target.endTime, other.startTime, other.endTime);
    }) ?? null;
  },

  /** Same-class slot overlap — exact slot match OR time-range overlap. */
  hasClassConflict(classId: string, day: TDay, slotId: string, excludeId?: string): TimetableEntry | null {
    const target = PERIOD_SLOTS.find(s => s.slotId === slotId);
    if (!target) return null;
    return _entriesCache.find(e => {
      if (e.classId !== classId || e.day !== day || e.id === excludeId) return false;
      if (e.slotId === slotId) return true;
      const other = PERIOD_SLOTS.find(s => s.slotId === e.slotId);
      if (!other) return false;
      return _timesOverlap(target.startTime, target.endTime, other.startTime, other.endTime);
    }) ?? null;
  },

  /** Validate then save (insert or update). Returns conflict reason on rejection. */
  async saveEntry(entry: Omit<TimetableEntry, 'id'> & { id?: string }): Promise<{ ok: boolean; conflict?: TimetableEntry; entry?: TimetableEntry; reason?: string }> {
    // Closed years are read-only unless the principal has explicitly
    // turned Correction Mode ON for this year (per-year, in-memory).
    // The UI useEditGuard prompts for a reason and writes the
    // YEAR_CORRECTION audit row before this point.
    if (_yearIsClosed && !(_activeYearId && useCorrectionStore.getState().isOn(_activeYearId))) {
      return { ok: false, reason: 'Academic year is closed' };
    }
    const teacher = _teachersCache.find(t => t.id === entry.teacherId);
    if (entry.teacherId && !teacher) return { ok: false, reason: 'Teacher is inactive or not found' };

    // Conflict 1: same teacher booked in another class for the same day+slot.
    const teacherConflict = entry.teacherId
      ? this.hasConflict(entry.teacherId, entry.day, entry.slotId, entry.id)
      : null;
    if (teacherConflict) return { ok: false, conflict: teacherConflict, reason: 'Teacher already booked in another class' };

    // Conflict 2: this class already has a different subject/teacher in this slot.
    const classConflict = this.hasClassConflict(entry.classId, entry.day, entry.slotId, entry.id);
    if (classConflict) return { ok: false, conflict: classConflict, reason: 'Class already has an entry in this slot' };

    if (!_activeYearId) throw new Error('No active academic year');

    // section_id resolution lives on the server (server/routes/timetable.ts
    // already does it). The previous client-side lookup was redundant and
    // made every "Allot" tap fire two extra Supabase round-trips before the
    // POST — a noticeable lag on slow connections.

    try {
      await apiTimetable.save({
        id:             entry.id,
        academicYearId: _activeYearId!,
        className:      entry.className,
        section:        entry.section,
        classId:        entry.classId,
        day:            entry.day,
        slotId:         entry.slotId,
        subject:        entry.subject,
        teacherId:      entry.teacherId || null,
        teacherName:    entry.teacherName,
        room:           entry.room,
        entryKind:      entry.entryKind,
      });
    } catch (e) {
      return { ok: false, reason: (e as Error).message };
    }
    void logAudit('timetable_saved', 'timetable_entry', entry.id ?? 'new', {
      classId: entry.classId, day: entry.day, slot: entry.slotId,
    });
    // Reload only what changed (entries) instead of reloading active year +
    // periods + teachers as well — those don't change on a single save.
    await _loadEntries(getSchoolId());
    const saved = _entriesCache.find(e =>
      e.classId === entry.classId && e.day === entry.day && e.slotId === entry.slotId
    );
    return { ok: true, entry: saved };
  },

  async deleteEntry(id: string): Promise<void> {
    // Same closed-year + correction-mode guard as saveEntry — the service
    // layer is the final enforcement boundary, even though the UI wraps
    // this in useEditGuard.gate().
    if (_yearIsClosed && !(_activeYearId && useCorrectionStore.getState().isOn(_activeYearId))) {
      throw new Error('Academic year is closed');
    }
    await apiTimetable.deleteEntry(id);
    // Same as saveEntry — only entries change on a delete; AY/periods/teachers
    // don't, so don't pay for re-loading them.
    await _loadEntries(getSchoolId());
  },

  /** Local-only edit of a slot's time (in-memory). For DB persistence, add a periods CRUD. */
  updateSlotTime(slotId: string, startTime: string, endTime: string): void {
    PERIOD_SLOTS = PERIOD_SLOTS.map(s => s.slotId === slotId ? { ...s, startTime, endTime } : s);
  },

  /** Resolved slot list for a specific class (or school default when
   *  className is null/empty). Per-class rows override the default —
   *  see migration 0108. */
  getSlotsForClass(className: string | null): PeriodSlot[] {
    return _resolveSlotsForClass(className && className.trim() ? className : null);
  },

  /** Add a single custom slot to a class (or the school default when
   *  className is null). Used by the "Add Period" button when the
   *  customization toggle is on. */
  async addCustomSlot(input: {
    className: string | null;
    name: string;
    startTime: string;
    endTime: string;
    type: SlotType;
  }): Promise<string> {
    if (!_activeYearId) throw new Error('No active academic year');
    const sortOrder = _periodRows
      .filter(r => (r.class_name ?? null) === (input.className ?? null))
      .reduce((m, r) => Math.max(m, r.sort_order), -1) + 1;
    const { id } = await apiTimetable.addPeriod({
      academicYearId: _activeYearId,
      className: input.className,
      name: input.name,
      startTime: input.startTime,
      endTime: input.endTime,
      periodType: input.type,
      sortOrder,
    });
    await _loadPeriods(getSchoolId());
    return id;
  },

  /** Update one slot's name, time and/or type. Used by the slot-edit
   *  modal so the principal can rename "Period 3" → "Prayer", change
   *  its time, or flip its type. */
  async updateSlot(slotId: string, patch: {
    name?: string; startTime?: string; endTime?: string; type?: SlotType;
  }): Promise<void> {
    await apiTimetable.updatePeriod({ slotId, ...patch });
    await _loadPeriods(getSchoolId());
  },

  /** Delete one slot — only allowed if it has no timetable_entries
   *  referencing it (server enforces). Use case: principal added a
   *  custom slot and wants to remove it. */
  async deleteSlot(slotId: string): Promise<void> {
    await apiTimetable.deletePeriod(slotId);
    await _loadPeriods(getSchoolId());
  },

  /** Bulk-replace the school's period definitions for the active year.
   *  Wipes existing rows and inserts the new layout atomically server-
   *  side. Reloads the in-memory cache after so the timetable grids
   *  reflect the new structure without a page refresh.
   *
   *  NOTE: timetable_entries reference slot_id (the row UUID). Wiping +
   *  re-inserting periods orphans every previously-scheduled entry —
   *  callers must warn the principal that existing entries will be
   *  cleared when the schedule shape changes. */
  async saveSchoolPeriods(periods: Array<{
    name: string; startTime: string; endTime: string;
    periodType: 'CLASS' | 'BREAK' | 'LUNCH' | 'ASSEMBLY';
  }>): Promise<void> {
    if (!_activeYearId) throw new Error('No active academic year');
    await apiTimetable.savePeriods({
      academicYearId: _activeYearId,
      periods,
    });
    await _loadPeriods(getSchoolId());
  },

  getClassWeeklyMap(classId: string, _academicYearId?: string): Record<TDay, TimetableEntry[]> {
    const entries = this.getClassTimetable(classId);
    const map = {} as Record<TDay, TimetableEntry[]>;
    for (const day of DAYS) {
      map[day] = entries.filter(e => e.day === day).sort((a, b) => {
        const ai = PERIOD_SLOTS.findIndex(s => s.slotId === a.slotId);
        const bi = PERIOD_SLOTS.findIndex(s => s.slotId === b.slotId);
        return ai - bi;
      });
    }
    return map;
  },

  getTodayForTeacher(teacherId: string, _academicYearId?: string): (TimetableEntry & { slot: PeriodSlot })[] {
    const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] as const;
    // Use IST day-of-week so a teacher in UTC at 19:30 (= IST 01:00 next day)
    // sees tomorrow's schedule, matching the rest of the app's date model.
    const istDow = new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata', weekday: 'long' });
    const today = (days.find(d => d === istDow) ?? days[new Date().getDay()]) as TDay;
    return _entriesCache
      .filter(e => e.teacherId === teacherId && e.day === today)
      .map(e => ({ ...e, slot: PERIOD_SLOTS.find(s => s.slotId === e.slotId)! }))
      .filter(e => e.slot)
      .sort((a, b) => a.slot.startTime.localeCompare(b.slot.startTime));
  },
};
